AWSTemplateFormatVersion: 2010-09-09
Description: pinpoint-campaign-metadata
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  PinpointProjectId:
    Type: String
    Description: Amazon Pinpoint Project ID to pull Campaign and Journey Information
      from
Resources:
  CampaignTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: ApplicationId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: ApplicationId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  JourneyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: ApplicationId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: ApplicationId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that writes Pinpoint Campaign and Journey Metadata
        to DynamoDB.
      Runtime: nodejs14.x
      Handler: src/handlers/pinpoint-metadata-handler.handler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          PINPOINT_APPID:
            Ref: PinpointProjectId
          CAMPAIGN_TABLE:
            Ref: CampaignTable
          JOURNEY_TABLE:
            Ref: JourneyTable
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Sid: PinpointReadMetadata
          Effect: Allow
          Action:
          - mobiletargeting:ListJourneys
          - mobiletargeting:GetCampaigns
          Resource:
          - Fn::Sub: arn:aws:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/${PinpointProjectId}*
          - Fn::Sub: arn:aws:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/${PinpointProjectId}
        - Sid: DynamoWrite
          Effect: Allow
          Action:
          - dynamodb:PutItem
          Resource:
          - Fn::GetAtt:
            - CampaignTable
            - Arn
          - Fn::GetAtt:
            - JourneyTable
            - Arn
      CodeUri: s3://davelem-scratchpad-build-artifacts/fc3b961bd1dc5f16f911b26a883f135f
Outputs:
  CampaignTable:
    Description: Campaign DynamoDB Table
    Value:
      Ref: CampaignTable
  JourneyTable:
    Description: Journey DynamoDB Table
    Value:
      Ref: JourneyTable
